version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    working-directory: lambda
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    working-directory: lambda
    commands:
      - echo "Packaging Lambda function..."
      - mkdir -p ../build
      - zip -r ../build/lambda.zip . -x "node_modules/aws-sdk/*"

  build:
    working-directory: lambda
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code \
          --function-name test \
          --zip-file fileb://build/lambda.zip \
          --region us-east-1

  post_build:
    working-directory: lambda
    commands:
      - echo "Build completed on $(date)"
      - echo "Lambda function updated successfully."

artifacts:
  files:
    - build/lambda.zip
