version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - echo "Nothing to install for this dummy build"
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
  build:
    commands:
      - echo "Building the project..."
      - echo "Hello from CodeBuild! This proves the webhookkkk workssssss."
  post_build:
    commands:
      - echo "Build completed on `dateeeeeeeeee`"
